"""Standalone ablation experiment script.

Reads train artifacts from ``models/`` generated by ``train_model.py`` and writes
ablation results to ``results/ablation_results.csv``.
"""

import os
import time

import joblib
import numpy as np
import pandas as pd
import xarray as xr
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from core import project_config as config

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MODELS_DIR = os.path.join(BASE_DIR, "models")
SUMMER_MODELS_DIR = getattr(config, "SUMMER_MODELS_DIR", MODELS_DIR)
RESULTS_DIR = os.path.join(BASE_DIR, "results")
os.makedirs(RESULTS_DIR, exist_ok=True)

DATA_NPZ_PATH = getattr(config, "DATA_NPZ_PATH", os.path.join(SUMMER_MODELS_DIR, "train_test_data.npz"))
DEM_REF_NC = getattr(config, "DEM_REF_NC", os.path.join(SUMMER_MODELS_DIR, "dem_reference.nc"))
TIME_NC = getattr(config, "TIME_NC", os.path.join(SUMMER_MODELS_DIR, "time_index.nc"))
OBS_NC = getattr(config, "OBS_NC", os.path.join(SUMMER_MODELS_DIR, "obs_for_plot.nc"))
IMERG_NC = getattr(config, "IMERG_NC", os.path.join(SUMMER_MODELS_DIR, "imerg_for_plot.nc"))
U10_NC = getattr(config, "U10_NC", os.path.join(SUMMER_MODELS_DIR, "u10_for_plot.nc"))
V10_NC = getattr(config, "V10_NC", os.path.join(SUMMER_MODELS_DIR, "v10_for_plot.nc"))
TCWV_NC = getattr(config, "TCWV_NC", os.path.join(SUMMER_MODELS_DIR, "tcwv_for_plot.nc"))


def _log(msg):
    print(msg, flush=True)


def metrics(y_true, y_pred):
    return [
        r2_score(y_true, y_pred),
        np.sqrt(mean_squared_error(y_true, y_pred)),
        mean_absolute_error(y_true, y_pred),
        np.mean(y_pred - y_true),
    ]


def _ablation_model_path(name):
    safe_name = name.lower().replace("+", "_plus_").replace("-", "_")
    safe_name = safe_name.replace(" ", "_")
    return os.path.join(SUMMER_MODELS_DIR, f"ablation_rf_{safe_name}.joblib")


def get_unified_sample_indices(
    imerg_da,
    u_da,
    v_da,
    q_da,
    dem_da,
    obs_da,
    time_mask,
    max_per_time=2000,
    random_state=42,
):
    """Per-time-step flat indices with finite predictors + obs."""
    rng = np.random.RandomState(random_state)
    dem2d = dem_da.transpose("lat", "lon").values
    dem_valid = np.isfinite(dem2d)
    out = {}
    for t_idx in np.where(time_mask)[0]:
        im = imerg_da.isel(time=t_idx).transpose("lat", "lon").values
        u = u_da.isel(time=t_idx).transpose("lat", "lon").values
        v = v_da.isel(time=t_idx).transpose("lat", "lon").values
        q = q_da.isel(time=t_idx).transpose("lat", "lon").values
        ob = obs_da.isel(time=t_idx).transpose("lat", "lon").values
        mask = (
            np.isfinite(im)
            & np.isfinite(u)
            & np.isfinite(v)
            & np.isfinite(q)
            & dem_valid
            & np.isfinite(ob)
        )
        valid_flat = np.flatnonzero(mask.ravel())
        if valid_flat.size == 0:
            continue
        if valid_flat.size <= max_per_time:
            chosen = valid_flat
        else:
            chosen = rng.choice(valid_flat, size=max_per_time, replace=False)
            chosen.sort()
        out[int(t_idx)] = chosen
    return out


def build_ablation_X_fixed(
    imerg_da,
    u_da,
    v_da,
    q_da,
    dem_da,
    obs_da,
    time_mask,
    config_vars,
    unified_indices,
):
    """Stack X, y using precomputed flat indices per timestep."""
    dem2d = dem_da.transpose("lat", "lon").values
    X_list, y_list = [], []
    for t_idx in sorted(unified_indices.keys()):
        if not time_mask[t_idx]:
            continue
        idx_flat = unified_indices[t_idx]
        ob = obs_da.isel(time=t_idx).transpose("lat", "lon").values.ravel()[idx_flat]
        feats = []
        if "IMERG" in config_vars:
            feats.append(
                imerg_da.isel(time=t_idx).transpose("lat", "lon").values.ravel()[idx_flat]
            )
        if "u10" in config_vars:
            feats.append(
                u_da.isel(time=t_idx).transpose("lat", "lon").values.ravel()[idx_flat]
            )
        if "v10" in config_vars:
            feats.append(
                v_da.isel(time=t_idx).transpose("lat", "lon").values.ravel()[idx_flat]
            )
        if "tcwv" in config_vars:
            feats.append(
                q_da.isel(time=t_idx).transpose("lat", "lon").values.ravel()[idx_flat]
            )
        if "DEM" in config_vars:
            feats.append(dem2d.ravel()[idx_flat])
        X = np.stack(feats, axis=1)
        X_list.append(X)
        y_list.append(ob)

    if not X_list:
        raise ValueError(
            f"Empty ablation sample for config_vars={config_vars}: check masks and data."
        )
    return np.concatenate(X_list), np.concatenate(y_list)


def run_ablation():
    _log("[ablation] start")
    t0 = time.perf_counter()

    # Baseline whole-province metrics from train_model results (same test rows).
    data = np.load(DATA_NPZ_PATH)
    X_train = data["X_train"]
    y_train = data["y_train"]
    X_test = data["X_test"]
    y_test = data["y_test"]
    raw_pred = data["raw_pred"]
    rf_pred = data["rf_pred"]
    _log("[ablation] training LR-Full model from NPZ train split ...")
    lr_model = LinearRegression().fit(X_train, y_train)
    _log(f"[ablation] LR-Full retrained: n_train={len(y_train)}, n_test={len(y_test)}")
    lr_pred = lr_model.predict(X_test)

    dem_da = xr.open_dataarray(DEM_REF_NC)
    obs_da = xr.open_dataarray(OBS_NC)
    imerg_da = xr.open_dataarray(IMERG_NC)
    u10_da = xr.open_dataarray(U10_NC)
    v10_da = xr.open_dataarray(V10_NC)
    tcwv_da = xr.open_dataarray(TCWV_NC)
    time_ds = xr.open_dataset(TIME_NC)

    train_mask = time_ds.time.dt.year.isin(config.TRAIN_YEARS) & time_ds.time.dt.month.isin(
        config.SUMMER_MONTHS
    )
    test_mask = time_ds.time.dt.year.isin(config.TEST_YEARS) & time_ds.time.dt.month.isin(
        config.SUMMER_MONTHS
    )
    train_tm = train_mask.values
    test_tm = test_mask.values

    max_pt = getattr(config, "MAX_SAMPLES_PER_TIME", 2000)
    rs = config.RANDOM_STATE
    train_indices = None
    test_indices = get_unified_sample_indices(
        imerg_da,
        u10_da,
        v10_da,
        tcwv_da,
        dem_da,
        obs_da,
        test_tm,
        max_per_time=max_pt,
        random_state=rs,
    )
    n_test_unified = int(sum(len(v) for v in test_indices.values()))
    _log(
        f"[ablation] unified indices: test {len(test_indices)} days, "
        f"samples={n_test_unified}"
    )
    if n_test_unified != int(len(y_test)):
        raise ValueError(
            "Test sample mismatch: unified ablation samples "
            f"({n_test_unified}) != NPZ y_test ({len(y_test)}). "
            "Please regenerate artifacts so train/test splits are aligned."
        )

    ablation_configs = [
        ("IMERG", ["IMERG"]),
        ("IMERG+DEM", ["IMERG", "DEM"]),
        ("IMERG+ERA5", ["IMERG", "u10", "v10", "tcwv"]),
    ]

    rows = [
        ["Raw IMERG"] + metrics(y_test, raw_pred),
    ]
    rf_n_jobs = getattr(config, "MAKE_TABLES_RF_N_JOBS", -1)
    for name, cfg_vars in ablation_configs:
        _log(f"[ablation] running {name} ...")
        Xte, yte = build_ablation_X_fixed(
            imerg_da,
            u10_da,
            v10_da,
            tcwv_da,
            dem_da,
            obs_da,
            test_tm,
            cfg_vars,
            test_indices,
        )
        model_path = _ablation_model_path(name)
        if os.path.exists(model_path):
            _log(f"[ablation]   loading model: {model_path}")
            rf = joblib.load(model_path)
            n_train_txt = "cached"
        else:
            _log(f"[ablation]   training model (cache miss): {model_path}")
            if train_indices is None:
                train_indices = get_unified_sample_indices(
                    imerg_da,
                    u10_da,
                    v10_da,
                    tcwv_da,
                    dem_da,
                    obs_da,
                    train_tm,
                    max_per_time=max_pt,
                    random_state=rs,
                )
                _log(f"[ablation] unified indices: train {len(train_indices)} days")
            Xtr, ytr = build_ablation_X_fixed(
                imerg_da,
                u10_da,
                v10_da,
                tcwv_da,
                dem_da,
                obs_da,
                train_tm,
                cfg_vars,
                train_indices,
            )
            rf = RandomForestRegressor(
                n_estimators=config.N_ESTIMATORS,
                random_state=config.RANDOM_STATE,
                n_jobs=rf_n_jobs,
            )
            rf.fit(Xtr, ytr)
            joblib.dump(rf, model_path)
            _log(f"[ablation]   saved model: {model_path}")
            n_train_txt = str(len(ytr))
        pred = rf.predict(Xte)
        rows.append([name] + metrics(yte, pred))
        _log(f"[ablation]   {name}: n_train={n_train_txt}, n_test={len(yte)}")

    rows.append(["LR-Full (retrained)"] + metrics(y_test, lr_pred))
    rows.append(["RF-Full"] + metrics(y_test, rf_pred))

    out_df = pd.DataFrame(rows, columns=["Model", "R2", "RMSE", "MAE", "Bias"])
    out_csv = os.path.join(RESULTS_DIR, "ablation_results.csv")
    out_df.to_csv(out_csv, index=False)

    _log(f"[ablation] wrote {out_csv}")
    _log(f"[ablation] finished in {time.perf_counter() - t0:.1f}s")
    print(out_csv)
    return out_csv


if __name__ == "__main__":
    run_ablation()
